name: ShellCheck

# Define the events that trigger the workflow
on:
  # Run the workflow when a .sh file is pushed to the repository
  push:
    paths:
      - "**.sh"
  # Run the workflow when a pull request includes changes to .sh files
  pull_request:
    paths:
      - "**.sh"
  # Allow manual execution of the workflow
  workflow_dispatch:
  # Schedule the workflow to run every 7 days at 00:00 UTC
  schedule:
    - cron: "0 0 */7 * *" # Runs at midnight UTC every 7 days

# Define the jobs in the workflow
jobs:
  # Job to run ShellCheck on shell scripts
  shellcheck:
    # Use the latest Ubuntu runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Run ShellCheck to lint shell scripts
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
